Simple machine learning
BaseWebDev/HT_10 pull request #1
Opened 2018-05-07 11:35 UTC by SermusAnton

2018-05-09 07:49 UTC, ilpoli requested changes

2018-05-09 07:49 UTC, ilpoli commented on SimpleLINQ/TF_IDF.cs
> +                data.SelectMany(d => d)
вероятность в каждом документе отдельно, т.е. в первом документе вероятность слова может быть 0.1, а во втором 0. у тебя же получается вероятность во всех документах встретить слово.

2018-05-12 22:49 UTC, SermusAnton commented
Исправил

2018-06-06 11:07 UTC, ilpoli approved these changes

2018-06-06 13:49 UTC, merged